create schema IF NOT EXISTS cleverbank;
create table IF NOT EXISTS cleverbank.banks
(
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY not null,
    bank_name text UNIQUE
);
create table IF NOT EXISTS cleverbank.users
(
    id              int GENERATED BY DEFAULT AS IDENTITY not null primary key,
    user_name       varchar(30),
    user_surname    varchar(30),
    user_middlename varchar(30)
);
create table IF NOT EXISTS cleverbank.scores
(
    id           int GENERATED BY DEFAULT AS IDENTITY not null primary key,
    score_number varchar(10) UNIQUE,
    bank_id      int                                  not null references cleverbank.banks (id) on delete cascade,
    currency     varchar(3),
    balance      money,
    user_id      int                                  not null references cleverbank.users (id) on delete cascade
);
create table IF NOT EXISTS cleverbank.transactions
(
    id              int GENERATED BY DEFAULT AS IDENTITY not null primary key,
    sender_score    int                                  not null references cleverbank.scores (id) on delete cascade,
    recipient_score int                                  not null references cleverbank.scores (id) on delete cascade,
    transfer_amount money
);