create schema cleverbank;
create table cleverbank.banks
(
    bank_id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY not null,
    bank_name text
);
create table cleverbank.users
(
    user_id         int GENERATED BY DEFAULT AS IDENTITY not null primary key,
    user_name       varchar(30),
    user_surname    varchar(30),
    user_middlename varchar(30)
);
create table cleverbank.scores
(
    score_id     int GENERATED BY DEFAULT AS IDENTITY not null primary key,
    score_number varchar(10),
    bank_id      int                                  not null references cleverbank.banks (bank_id),
    currency     varchar(3),
    balance      money,
    user_id      int                                  not null references cleverbank.users (user_id)
);
create table cleverbank.transactions
(
    transaction_id  int GENERATED BY DEFAULT AS IDENTITY not null primary key,
    sender_score    int                                  not null references cleverbank.scores (score_id),
    recipient_score int                                  not null references cleverbank.scores (score_id),
    transfer_amount money
);